language: node_js
node_js:
- '8'
env:
  secure: 10DHZGhSxfkOdSkmLMqnEWTkxesXpnK/Tt/PPGvbF77HMMTBPpnbwIHedJ2G//4I9hILV9FuxwngI49kYFd6YeS8euWob8ZVWhRe0Z1fVd5/T58l40cbR9zTVBvDjZGSs06DzIVivrU+usk8Xz3Rf6q47zOsR58xCmovLobsUN990vDvQ5hPWALcgPZr8OCro7HjdgDABLJJv6iQmFQBSUwJ3HoJGu72zVJTflf9SwBV4uxaTLUQaOKspr/K8ZYkhgFIHSF3ghHWy/I3NcHRSjsRMmALjEnZdPva30cj1pZ+UdRpRlqOUL1ZpYyGj/SDO2pz89Cll8ConpvtjkLoHBvW6xd7YCIffwvYsxzlD9Vk/M01b7yydfdrrTQeu+8V2WV3MEz3FdWiA3ocPeb+6gbAqnwPf6tc6x7rfjf4E3Ed9mXvy6HfUbt0yxpdpM9FZS4rTJ2pnwqfQknI0WmRQpx2JV3kAK0TK29EdJjkkx1EzwY/ESM6DjPa0u+/i/cNBMDDrfqF2vB4nE9T9flGz4MLIZiX1yPKDlw0JZMEfLRfaC38M/nCgSZ+k+Mdjxj73BP5Z2rrOXWGokvha/Xa7rk3NjfzOuGMmiC6nthCpVjDlYa7Qx/kTu+1WqB76xcEN/h44T2LJMYsKZ2PLBJnUp//4eZ4mnWkTQrq6YhxkVk=
install:
- npm install
script:
- npm run deploy
